# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbnet < Formula
  desc "A database client that lets your SQL superpowers shine."
  homepage "https://github.com/dbnet-io/dbnet"
  version "0.0.38"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dbnet-io/dbnet/releases/download/v0.0.38/dbnet_darwin_arm64.tar.gz"
      sha256 "6ede0e130662f563d4df95dfdff02ffea7948d65890df78c1f002f2095d59117"

      def install
        bin.install "dbnet"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dbnet-io/dbnet/releases/download/v0.0.38/dbnet_darwin_amd64.tar.gz"
      sha256 "e3e1c7d903099785b184e5de4a1811082afa49c6ddeced3ec6a1e8d6d097fe61"

      def install
        bin.install "dbnet"
      end
    end
  end
end
