# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbnet < Formula
  desc "A database client that lets your SQL superpowers shine."
  homepage "https://github.com/dbnet-io/dbnet"
  version "0.0.42"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dbnet-io/dbnet/releases/download/v0.0.42/dbnet_darwin_arm64.tar.gz"
      sha256 "2324d5051dfdc753a8df2ce1bbd6552c61bb069c5b2b32367f3fb6028cb417ec"

      def install
        bin.install "dbnet"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dbnet-io/dbnet/releases/download/v0.0.42/dbnet_darwin_amd64.tar.gz"
      sha256 "50a7fd00586410cf45e81255684d9e80532f8997b05b70a580f8c6dc533c22fd"

      def install
        bin.install "dbnet"
      end
    end
  end
end
